-d D:\FPGA\Projects\button_test\impl\gwsynthesis\button_test.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\FPGA\Projects\button_test\src\button_test.cst
-cfg D:\FPGA\Projects\button_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
